# pipeline_config.yaml - Configuration of Pipelines that uses external catalogs


# Service instances - references to services catalog with custom settings
service_instances:
  - name: primary_blob_storage
    service_catalog_id: azure_storage_01 # Reference to service in catalog
    settings:
      account_name: ${AZURE_STORAGE_SERVICE_ACCOUNT_NAME}
      credential_type: ${AZURE_STORAGE_SERVICE_CREDENTIAL_TYPE}
      credential_key: ${AZURE_STORAGE_SERVICE_ACCOUNT_KEY}

  - name: primary_ai_inference_service
    service_catalog_id: azure_ai_inference_service_01
    settings:
      endpoint: ${AZURE_AI_INFERENCE_SERVICE_ENDPOINT}
      credential_type: ${AZURE_AI_INFERENCE_SERVICE_CREDENTIAL_TYPE}
      api_key: ${AZURE_AI_INFERENCE_SERVICE_API_KEY}
      model_name: "gpt-4.1-mini"
      max_tokens: 4000

pipelines:
  - name: pipeline_1
    description: 'A pipeline to extract, transform, and load documents from Azure Blob Storage to a database'
    version: '1.0'

    steps:
      - name: sample_step_1
        step_catalog_id: sample_step # Reference to step in catalog
        enabled: true
        services: [] # References to service instances
        settings:
          key1: "custom_value1"
          key2: "custom_value2"

      - name: pdf_to_png_1
        step_catalog_id: pdf_to_png
        enabled: true
        services: [primary_blob_storage] # References to service instances
        settings:
          png_output_folder: "./output/png"
          num_pages: 10
          dpi: 300
          image_format: "PNG"

      - name: pdf_page_png_to_markdown_1
        step_catalog_id: pdf_page_png_to_markdown
        enabled: true
        services: [primary_ai_inference_service, primary_blob_storage] # References to service instances
        settings:
          prompts:
            system: "You are an AI assistant that helps convert images of pages of a pdf document to markdown text. Only output valid markdown."
            user: "Extract the text from the following image into markdown and provide descriptions of images. Always format the markdown as follows to distinguish the text extracted from image descriptions:\n==Extracted-Text==\n{Insert extracted text as markdown here}\n\n==Image-Descriptions==\n{Insert image descriptions as markdown here}"
          max_completion_tokens: 4000
          temperature: 1.0
          top_p: 1.0
          frequency_penalty: 0.0
          presence_penalty: 0.0

    execution_sequence: [pdf_to_png_1, pdf_page_png_to_markdown_1]
    
    # Settings for the pipeline execution
    settings:
      enabled: true
      retry_delay: 5
      timeout: 300
      max_concurrent_runs: 5
      