# pipeline_config.yaml - Configuration of Pipelines that uses external catalogs


# Service instances - references to services catalog with custom settings
service_instances:
  - name: primary_blob_storage
    service_catalog_id: azure_storage_01 # Reference to service in catalog
    settings:
      account_name: ${AZURE_STORAGE_SERVICE_ACCOUNT_NAME}
      credential_type: ${AZURE_STORAGE_SERVICE_CREDENTIAL_TYPE}
      credential_key: ${AZURE_STORAGE_SERVICE_ACCOUNT_KEY}

  - name: primary_ai_inference_service
    service_catalog_id: azure_ai_inference_service_01
    settings:
      endpoint: ${AZURE_AI_INFERENCE_SERVICE_ENDPOINT}
      credential_type: ${AZURE_AI_INFERENCE_SERVICE_CREDENTIAL_TYPE}
      api_key: ${AZURE_AI_INFERENCE_SERVICE_API_KEY}
      model_name: "gpt-4.1-mini"
      max_tokens: 4000

  - name: primary_ai_search_service
    service_catalog_id: azure_ai_search_service_01
    settings:
      account_name: ${AZURE_AI_SEARCH_SERVICE_ACCOUNT_NAME}
      credential_type: ${AZURE_AI_SEARCH_SERVICE_CREDENTIAL_TYPE}
      api_key: ${AZURE_AI_SEARCH_SERVICE_API_KEY}
      api_version: "2025-05-01-preview" # Updated to the latest version
      index_name: "documents_index" # Name of the search index to use

pipelines:
  - name: pipeline_1
    description: 'A pipeline to extract, transform, and load documents from Azure Blob Storage to a database'
    version: '1.0'

    steps:
      - name: sample_step_1
        step_catalog_id: sample_step # Reference to step in catalog
        enabled: true
        services: [] # References to service instances
        fail_step_on_document_error: false # Fail the step if document processing fails, this is useful for debugging, if set to false, the pipeline will continue even if this step fails
        debug_mode: false # Enable debug mode for this step
        settings:
          key1: "custom_value1"
          key2: "custom_value2"

      - name: pdf_text_extractor_1
        step_catalog_id: pdf_text_extractor
        enabled: true
        services: [primary_blob_storage, primary_ai_inference_service] # References to service instances
        fail_step_on_document_error: true # Fail the step if document processing fails, this is useful for debugging, if set to false, the pipeline will continue even if this step fails
        debug_mode: true # Enable debug mode for this step
        settings:
          png_output_folder: "./output/png"
          num_pages: 3 # Maximum number of pages to convert (-1 = all pages)
          dpi: 300
          image_format: "PNG"
          prompts:
            system: "You are an AI assistant that helps convert images of pages of a pdf document to markdown text. Only output valid markdown."
            user: "Extract the text from the following image into markdown and provide descriptions of images. Always format the markdown as follows to distinguish the text extracted from image descriptions:\n==Extracted-Text==\n{Insert extracted text as markdown here}==End-Extracted-Text==\n\n==Image-Descriptions==\n{Insert image descriptions as markdown here}==End-Image-Descriptions=="
          max_completion_tokens: 4000
          temperature: 1.0
          top_p: 1.0
          frequency_penalty: 0.0
          presence_penalty: 0.0

      - name: custom_ai_prompt_1
        step_catalog_id: custom_ai_prompt
        enabled: true
        services: [primary_ai_inference_service] # References to service instances
        fail_step_on_document_error: true # Fail the step if document processing fails, this is useful for debugging, if set to false, the pipeline will continue even if this step fails
        debug_mode: true # Enable debug mode for this step
        settings:
          chunk_field_to_apply_prompt_on: markdown_text
          output_field_name: custom_ai_prompt_output
          prompts:
            system: "You are an AI assistant. Please process the input accordingly."
            user: "This is a custom AI prompt step. Please process the input accordingly.\nInput: {chunk_content}"
          max_completion_tokens: 4000
          temperature: 1.0
          top_p: 1.0
          frequency_penalty: 0.0
          presence_penalty: 0.0

      - name: ai_search_index_writer_1
        step_catalog_id: ai_search_index_writer
        enabled: true
        services: [primary_ai_search_service] # References to service instances
        fail_step_on_document_error: true # Fail the step if document processing fails, this is useful for debugging, if set to false, the pipeline will continue even if this step fails
        debug_mode: false # Enable debug mode for this step
        settings:
          index_name: "documents_index"
          chunks_iterator_field: "data.chunks_data"
          index_field_mappings: | 
                                  {
                                    "page_id": "id",
                                    "input_file_path": "file_name",
                                    "page_num": "page_num",
                                    "markdown": "markdown",
                                    "summary": "summary",
                                    "page_image_base64": "page_image"
                                  }
        

    execution_sequence: [pdf_text_extractor_1, custom_ai_prompt_1]
    
    # Global settings for the pipeline execution
    settings:
      enabled: true
      retry_delay: 5
      timeout: 300
      max_concurrent_runs: 5